name: Deploy Repos A and B

on:
  push:
    branches:
      - '!main'
      - 'feature_branch'

jobs:
  deploy-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from Repo A
        uses: actions/checkout@v2
        with:
          repository: kalpanauppara/regional2_repo
          ref: feature_branch
          working-directory: ${{ github.workspace }}

      - name: Clone and copy from Repo A
        run: |
          mkdir content_repo1
          cp -R sfdx-sample-code content_repo1
          ls -lrt content_repo1
          cd sfdx-sample-code 
          ls -lrt
        working-directory: ${{ github.workspace }}

      - name: Install Salesforce CLI (SFDX)
        run: |
          # Download and install Salesforce CLI
          wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/install.sh | bash

      - name: Install SFDX-Scanner
        run: sfdx plugins:install @salesforce/sfdx-scanner

      # ... other steps ...

      - name: Debug Workspace Contents
        run: |
            cd ${{ github.workspace }}
            ls -R

      - name: Debug Salesforce Project Directory
        run: |
          cd ${{ github.workspace }}/sfdx-sample-code/force-app
          ls -R

      - name: Deploy to Salesforce
        run: |
          # Deploy to Salesforce
          cd ${{ github.workspace }}/content_repo1/sfdx-sample-code
          sfdx force:source:deploy --targetusername ${{ secrets.SALESFORCE_DEVHUB_USERNAME }} --sourcepath "kalpanauppara/regional2_repo/tree/feature_branch/sfdx-sample-code/force-app"  --apiversion ${{secrets.API_VERSION}} --wait 90 -c --json > validate.json
