name: Deploy Repos A and B

on:
  push:
    branches:
      - '!main'
      - 'feature_branch'

jobs:
  deploy-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from Repo A
        uses: actions/checkout@v2
        with:
          repository: kalpanauppara/MyTest_Deploy
          ref: feature_branch
          working-directory: ${{ github.workspace }}

      - name: Checkout code from Repo B
        uses: actions/checkout@v2
        with:
          repository: kalpanauppara/regional2_repo
          ref: feature_branch
          working-directory: ${{ github.workspace }}

      - name: List contents of content_repo2
        run: |
              ls -lrt content_repo2
              cd sfdx-sample-code
              ls -lrt
        

      - name: Install SFDX CLI
        run: npm install sfdx-cli --global
      
      - name: Install SFDX-Scanner
        run: sfdx plugins:install @salesforce/sfdx-scanner

      - name: Install SFDX-Git-Delta plugin
        run: |
          echo y | sfdx plugin:install sfdx-git-delta
          sfdx plugins

      - name: Authenticate with Salesforce
        run: |
          # Authenticate with Salesforce using the connected app credentials
          sfdx force:auth:jwt:grant -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME }} -i ${{ secrets.SALESFORCE_JWT_SECRET_KEY }} -s ${{ secrets.SALESFORCE_CONSUMER_KEY }}
        working-directory: ${{ github.workspace }}

      - name: Deploy to Salesforce
        run: |
          # Deploy to Salesforce
          sfdx force:source:deploy -p content_deploy/ -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME }}
        working-directory: ${{ github.workspace }}
