name: Deploy Repos A and B

on:
  push:
    branches:
      - '!main'
      - 'feature_branch'

jobs:
  deploy-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from Repo A
        uses: actions/checkout@v2
        with:
          repository: kalpanauppara/MyTest_Deploy
          ref: feature_branch
          path: kalpanauppara/MyTest_Deploy

      - name: Checkout code from Repo B
        uses: actions/checkout@v2
        with:
          repository: kalpanauppara/regional2_repo
          ref: feature_branch
          path: kalpanauppara/regional2_repo/sfdx-sample-code

      - name: List Workspace Content
        run: |
            cd ${{ github.workspace }}
            pwd
            cd kalpanauppara/regional2_repo/sfdx-sample-code/force-app
            ls -lrt

      - name: Install SFDX CLI
        run: npm install sfdx-cli --global
      
      - name: Install SFDX-Scanner
        run: sfdx plugins:install @salesforce/sfdx-scanner

      - name: Install SFDX-Git-Delta plugin
        run: |
          echo y | sfdx plugin:install sfdx-git-delta
          sfdx plugins

      - name: Create JWT Key File
        run: echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > jwt-key.pem

      - name: Authenticate with Salesforce
        run: |
          # Authenticate with Salesforce using the connected app credentials
          sfdx force:auth:jwt:grant -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME }} -i ${{ secrets.SALESFORCE_CONSUMER_KEY }} -f jwt-key.pem --setdefaultdevhubusername --setalias devjwt

      - name: Deploy to Salesforce
        run: |
          # Deploy to Salesforce
          cd ${{ github.workspace }}/repo-a/sfdx-sample-code
          sfdx force:source:deploy --targetusername ${{ secrets.SALESFORCE_DEVHUB_USERNAME }} --sourcepath "force-app"  --apiversion ${{secrets.API_VERSION}} --wait 90 -c --json > validate.json
