name: Deploy Repos A and B

on:
  push:
    branches:
      - '!main'
      - 'feature_branch'

jobs:
  deploy-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from Repo A
        uses: actions/checkout@v2
        with:
          repository: kalpanauppara/regional2_repo
          ref: feature_branch
          working-directory: ${{ github.workspace }}

      - name: Clone and copy from Repo A
        run: |
          mkdir content_repo1
          cp -R sfdx-sample-code content_repo1
          ls -lrt content_repo1
          cd sfdx-sample-code 
          ls -lrt
        working-directory: ${{ github.workspace }}

      - name: Install SFDX CLI Nightly
        run: |
          # Download and install the nightly version of SFDX
          wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/nightly/install.sh | bash

      - name: Install SFDX-Scanner
        run: sfdx plugins:install @salesforce/sfdx-scanner

      - name: Install SFDX-Git-Delta plugin
        run: |
          echo y | sfdx plugin:install sfdx-git-delta
          sfdx plugins

      - name: Create JWT Key File
        run: echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > jwt-key.pem

      - name: Authenticate with Salesforce
        run: |
          # Authenticate with Salesforce using the connected app credentials
          sfdx force:auth:jwt:grant -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME }} -i ${{ secrets.SALESFORCE_CONSUMER_KEY }} -f jwt-key.pem --setdefaultdevhubusername --setalias devjwt

      - name: Debug Workspace Contents
        run: |
            cd ${{ github.workspace }}
            ls -R

      - name: Debug Salesforce Project Directory
        run: |
          cd ${{ github.workspace }}/sfdx-sample-code/force-app
          ls -R

      - name: Deploy to Salesforce
        run: |
          # Deploy to Salesforce
          cd ${{ github.workspace }}/content_repo1/sfdx-sample-code
          sfdx force:source:deploy --targetusername ${{ secrets.SALESFORCE_DEVHUB_USERNAME }} --sourcepath "kalpanauppara/regional2_repo/tree/feature_branch/sfdx-sample-code/force-app"  --apiversion ${{secrets.API_VERSION}} --wait 90 -c --json > validate.json
