name: Deploy Repos A and B

on:
  push:
    branches:
      - '!main'
      - 'feature_branch'

jobs:
  deploy-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from Repo A
        uses: actions/checkout@v2
        with:
          repository: kalpanauppara/regional2_repo
          ref: feature_branch
          working-directory: ${{ github.workspace }}

        # This step will check out the specified branch or commit from Repo A

      - name: Clone and copy from Repo A
        run: |
          mkdir content_repo1
          cp -R sfdx-sample-code content_repo1
          ls -lrt content_repo1
          cd sfdx-sample-code 
          ls -lrt
        working-directory: ${{ github.workspace }}
        # Replace 'path/to/your/folder1' with the actual path to the folder you want to copy from Repo A

      - name: Checkout code from Repo B
        uses: actions/checkout@v2
        with:
          repository: kalpanauppara/MyTest_Deploy
          ref: feature_branch
          working-directory: ${{ github.workspace }}

        # This step will check out the specified branch or commit from Repo A

      - name: Clone and copy from Repo B
        run: |
             mkdir content_repo2
             cp manifest/package.xml content_repo2
             cd content_repo2 
             ls -lrt
      
      - name: Install SFDX CLI
        run: npm install sfdx-cli --global
      
      - name: Install SFDX-Scanner
        run: sfdx plugins:install @salesforce/sfdx-scanner

      - name: Install SFDX-Git-Delta plugin
        run: |
          echo y | sfdx plugin:install sfdx-git-delta
          sfdx plugins

      - name: Create JWT Key File
        run: echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > jwt-key.pem

      - name: Authenticate with Salesforce
        run: |
          # Authenticate with Salesforce using the connected app credentials
          sfdx force:auth:jwt:grant -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME }} -i ${{ secrets.SALESFORCE_CONSUMER_KEY }} -f jwt-key.pem --setdefaultdevhubusername --setalias devjwt
     
      - name: Debug Workspace Contents
        run: |
            cd ${{ github.workspace }}
            ls -R

      - name: Debug Salesforce Project Directory
        run: |
          cd manifest/
          ls -R

      - name: Deploy to Salesforce
        run: |
          # Deploy to Salesforce
          cd manifest
          ls -lrt
          #sfdx force:source:deploy --targetusername ${{ secrets.SALESFORCE_DEVHUB_USERNAME }} --sourcepath "force-app"  --apiversion ${{secrets.API_VERSION}} --wait 90 -c --json > validate.json
          sfdx force:source:deploy -x manifest --sourcepath "force-app"

